### ISSUE TITLE
Using sourcemaps is coming back with "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by StephenBloomquist** [harold-b/vscode-duktape-debug#11]
I've encountered this with typescript code as simple as:
```
class EmptyClass { }
function main() {
    let t = new EmptyClass();
}
```

The debugger can step through code just fine for declaring/using standard variables, It also handles function calls just fine from what I can tell (even a call to a static function in a class), but I keep getting an "Unexpected end of JSON input" error whenever a class tries to instantiate.

Something additional you might find interesting:
```
class StaticFunction {
    static example() { let t = 0; }
}

function main() {
    StaticFunction.example();
}
```

If I step the debugger into the example() static function and try to expand the "this: Function" local variable, the same error occurs. I was able to get a screencap before the UI was nuked:
![vscode_duktape_debugger_sourcemaps_error1](https://cloud.githubusercontent.com/assets/24838721/21657192/08de2806-d276-11e6-83a2-6370bc4a737a.png)

That `ÿ` is interesting. Doing a quick search on that character and JSON files yielded me these:
http://stackoverflow.com/questions/30596681/json-parsing-unexpected-character-%C3%BF-at-position-0
http://stackoverflow.com/questions/37294273/failed-to-parse-template-error-parsing-json-invalid-character-%C3%BF-looking-for

Not sure how applicable it is here but it feels like it could relevant.

**Comment by harold-b** [comment]
The `ÿ` is here representative of the `0xFF` character which are duktape internal properties which are inaccessible from Ecmascript. The 0xFF character makes them invalid UTF-8 so I wonder if there were some recent changes that would mess up something when the return events have these properties...

Strange because I use internal properties in pretty much all my custom object and I haven't ever had this issue. Any idea where (which function/last call) it happened?

**Comment by StephenBloomquist** [comment]
I'm still in the process of looking but so far I've been able to track things as recent as the sendResponse() in returnVars() in variableRequests().

I stringified the response body before it was sent and, after some quick manual formatting, got this: 
```
{
    "variables":[
        {
            "name":"__artificial",
            "value":"{...}",
            "variablesReference":1002
        },
        {
            "name":"example",
            "value":"Function",
            "variablesReference":1006
        },
        {
            "name":"fileName",
            "value":"\"Script.js\"",
            "variablesReference":0
        },
        {
            "name":"length",
            "value":"0",
            "variablesReference":0
        },
        {
            "name":"name",
            "value":"\"StaticFunction\"",
            "variablesReference":0
        },
        {
            "name":"prototype",
            "value":"Object",
            "variablesReference":1005
        },
        {
            "name":"ÿFormals",
            "value":"Array",
            "variablesReference":1004
        },
        {
            "name":"ÿLexenv",
            "value":"DecEnv",
            "variablesReference":1003
        },
        {
            "name":"ÿPc2line",
            "value":"\u0001\u0000\u0000\u0000\u0003\u0000\u0000\u0000\f\u0000\u0000\u0000\u0000",
            "variablesReference":0
        }
    ]
}
```

Which... Seems fine? At least I'm not seeing anything immediate that would complain cause an unexpected end of JSON?

**Comment by StephenBloomquist** [comment]
You know, was just reading your general readme and I don't know why I didn't think about this until now... But I wonder if it may be a cause. I'm currently using Duktape 1.6.0

**Comment by StephenBloomquist** [comment]
Rebuilt my project with 1.5.0 and the problem is persisting. Though now that I think about it, I'm not sure how much duktape would have a hand in dealing with sourcemaps. Seems like it would be vscode's responsibility. Your extension seems to work more or less fine with 1.6.0 otherwise.

**Comment by harold-b** [comment]
Certainly possible, I have never tested with 1.6.0. Only 1.5.0, the next jump will be to 1.5.0.
However, checking the [diff](https://github.com/svaarala/duktape/compare/v1.5.0...v1.6.0#diff-df880d4c6b6e3b1ee1453743eba813eb) Only shows one change in `duk_debugger.c` that I don't believe should really affect anything. The debug protocol `debugger.rst` doesn't seem to be listed there either, so i think there doesn't seem to be any changes to the protocol bwteen 1.5.0 and 1.6.0...

**Comment by harold-b** [comment]
The runtime shouldn't need to worry about sourcemaps at all, this is all done in the client-side. The runtime only needs to make sure to specify the correct file name/path with the compile functions because that's what we use on the client-side to attempt to match it to the real file.

The only thing you won't get correctly with sourcemaps is exception message logs won't be mapped.  I don't think I map caught exceptions yet either, I can't recall.

**Comment by harold-b** [comment]
I'm setting up a test case here to see if I can reproduce real quick.

**Comment by StephenBloomquist** [comment]
Unfortunately I'm not sure how much closer I can get to where the actual "Unexpected end of JSON input. Stopping the debug adapter" error is thrown. I'm assuming after that sendResponse() the rest happens somewhere in the vscode debug adapter since (again I'm assuming) that's how variablesRequest() is reached in the first place.

**Comment by harold-b** [comment]
I can't reproduce at all... I messed with it a lot to no avail:
![debug-01](https://cloud.githubusercontent.com/assets/11462418/21661089/b91df656-d2a8-11e6-8758-8c818a7da3b5.gif)

**Comment by harold-b** [comment]
Are you using your modified source of client or the vanilla version?

**Comment by StephenBloomquist** [comment]
Wait, there's a difference there. I'm not calling main in the script. I'm calling it from the C++ side via duk_pcall:

```
int main() {
	duk_context* ctx = nullptr;
	TestDebugServer server;

	ctx = duk_create_heap_default();
	if (!ctx) {
		cout << "Failed to create a Duktape heap.\n";
		return 1;
	}

	server.Attach(ctx);

	if (duk_peval_file(ctx, "Script.js") != 0) {
		cout << "Error: " << duk_safe_to_string(ctx, -1) << endl;
		duk_destroy_heap(ctx);
		return 1;
	}
	duk_pop(ctx);

	duk_push_global_object(ctx);
	duk_get_prop_string(ctx, -1, "main");
	if (duk_pcall(ctx, 0) != 0) {
		cout << "Error: " << duk_safe_to_string(ctx, -1) << endl;
	}
	duk_pop(ctx);

	duk_destroy_heap(ctx);
	return 0;
}
```

The server class is, right now, just acting as a wrapper to the duk_trans_socket code.

**Comment by StephenBloomquist** [comment]
> Are you using your modified source of client or the vanilla version?
Vanilla, aside from all the _dbgLog entries I've put directly into the javascript for extra debugging while trying to figure this out.

**Comment by harold-b** [comment]
Still no luck :disappointed:  :

![debug-02](https://cloud.githubusercontent.com/assets/11462418/21662031/d4b66df8-d2ad-11e6-9fb7-83c825a96acd.gif)

Try with the vanilla extension, it makes it hard to isolate if it's not the same client code I'm running over here.

**Comment by harold-b** [comment]
Also, perhaps try the v1.5.0 duk.exe with the output file you get from typescript and see if that works.

**Comment by StephenBloomquist** [comment]
Interesting. So I completely reinstalled your extension and it worked (even with 1.6.0). After diffing the fresh DukDebugger.js with the one I was messing with, the only differences were the debug features. So I decided to try something. I changed this line (332):
`this._dbgLog = args.debugLog || false;`
to what I had it before:
`this._dbgLog = true; //args.debugLog || false;`
Something that I did as a quick way in the script to enable debug logging. This brought the issue back.

**Comment by harold-b** [comment]
Excellent, thanks! I could reproduce that one.
*BTW you can enable debugLog from your launch.json , just set `debugLog: true`.*

I suspect this is probably because the internal properties won't encode into valid UTF-8, so I'll have to scan for them when debugLog is enabled. I wonder if this was a recent change in the VSCode blackened since I always had the debugLog on when developing and testing and never encountered this even though there were tons of internal properties present.

I'll test with my current app. which has a lot of internal properties, to see if it happens there too.

**Comment by harold-b** [comment]
Yup, it happens there now too. Will barely let me start the debug session before that happens :stuck_out_tongue_closed_eyes: .

Thanks for the find. I suppose you can disable debugLog for now, before I issue a fix.
Or, if you'd like, just scan for the `msg` var in `dbgLog()` for the 0xFF char codes and drop those messages, or modify the msg.

**Comment by StephenBloomquist** [comment]
I saw that debug option was available via your code a while ago, but vscode doesn't seem to consider it a "valid" option in the json file. I didn't think it would work so I guess I never just tried it anyway.

I have some additional information with regards to oddities I've seen with the dbgLog function that may be useful. There are occasionally places in the code where a call to that function doesn't output anything but a newline. If I make the same call twice, such as:
```
_this.dbgLog("Hello world");
_this.dbgLog("Hello world");
```
the effective output looks something like
```
~~~ some log stuff ~~~

Hello world
~~~ some log stuff ~~~
```

It seemed mostly related to promises and `.then` situations.

**Comment by harold-b** [comment]
Yes, if I recall this was because output events needed to have a new line appended to them, which I did not want to in my own internal debug messages so I just appended it in the dbgLog function. However when logging an error or some other message gotten from elsewhere, it will probably have a new line already appended at the end.

The debugLog is more of an internal testing property so it's not exactly polished. It wasn't even in the release version originally, I just added it because I thought some users might find logging the traffic useful.

**Comment by StephenBloomquist** [comment]
Well what I just find interesting is that the _entire previous dbgLog call_ would not show up. I'd have to call it twice to get the log I was wanting to show up to show up.

**Comment by harold-b** [comment]
Oh I didn't notice you called it twice.

**Comment by StephenBloomquist** [comment]
Assuming none of my other dbgLog calls messed with it, you could try adding two consecutive calls to line... 937ish? Inside this:
```
return _this._dukProto.requestGetObjPropDescRange(propSet.heapPtr, 0, maxOwnProps)
                    .then(function (r) {
                    // !!!!!!!!!!!
                    // Right here!
                    // !!!!!!!!!!!
                    var props = [];
                    for (var i = 0; i < r.properties.length; i++) {
                        if (r.properties[i].value !== undefined)
                            props.push(r.properties[i]);
                    }
					_this.dbgLog("...1");
                    return _this.resolvePropertySetVariables(ArrayX.convert(props, function (v) { return String(v.key); }), ArrayX.convert(props, function (v) { return v.value; }), propSet)
                        .then(function (p) { _this.dbgLog(propSet.variables); return propSet.variables; });
                });
```
And see if you only get 1 log message.

**Comment by harold-b** [comment]
OK Thanks, I'll check it when I have some time.

In the meantime, here's a quick fix to add in `dbgLog` that will let you continue using it, it will replace invalid octets with a question mark:

``` javascript
var buf = Buffer.from( msg );
for( var i=0, len=buf.byteLength; i < len; i++ )
    if( buf[i] > 0x7F )
        buf[i] = 0x3F;

msg = buf.toString( 'utf8' );
```

Just added in `dbgLog` before the `msg` var is printed.

**Comment by StephenBloomquist** [comment]
Awesome, thanks!

**Comment by harold-b** [comment]
No problem, thanks for reporting these. :)

**Comment by StephenBloomquist** [comment]
It looks like it's `console.log` specifically that cares about the weird formatting. `OutputEvent` seems fine regardless.
