### ISSUE TITLE
VS Code UI out of step

### ISSUE THREAD

**Issue by willi1s** [harold-b/vscode-duktape-debug#12]
I've been working for a while without issues with my duktape running on the localhost, and so nice and quick, but now I have deployed duktape to an ARM based target board with IP over USB so the whole thing is a bit slower, and this has uncovered a number of issues.

I'm using `"stopOnEntry": true` to work around the fact that sometimes code runs before the break points are set, when I 'Attach', the code is correctly stopped at the top of the JavaScript file. I then set a breakpoint  and hit 'Resume'. The code runs and the breakpoint is hit, but VS Code still thinks it is running i.e. 'Pause' button is available, not 'step' or 'resume'. If I press 'Pause' I get 'Request failed: Already paused.'

Debug log is as follows:

> Establishing connection with Duktape at 192.168.1.80:9091
Connected. Verifying protocol...
Protocol: 1 10600 v1.6.0 SW terminal
Requesting target info...
OUT -> <REQ: 1> <0x10: BASICINFO>
Status Notification: PAUSE
IN <- <REP: 2> <int: 10600> <str: v1.6.0> <str: SW terminal> <int: 1> <int: 4> <EOM: 0> 
10600 v1.6.0 SW terminal Little
Attached to duktape debugger.
Finalized Initialization.
removeAllTargetBreakpoints
OUT -> <REQ: 1> <0x17: LISTBREAK>
[FE] setBreakPointsRequest
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 0> <EOM: 0> 
OUT -> <REQ: 1> <0x12: PAUSE>
[FE] configurationDoneRequest
[FE] threadsRequest
IN <- <REP: 2> <EOM: 0> 
Status Notification: PAUSE
[FE] threadsRequest
[FE] stackTraceRequest
OUT -> <REQ: 1> <0x1c: GETCALLSTACK>
IN <- <REP: 2> <str: message_box.js> <str: eval> <int: 1> <int: 0> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
[FE] scopesRequest
OUT -> <REQ: 1> <0x1d: GETLOCALS>
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
[FE] variablesRequest
[FE] setBreakPointsRequest
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 1> <EOM: 0> 
[FE] continueRequest
OUT -> <REQ: 1> <0x13: RESUME>
IN <- <REP: 2> <EOM: 0> 
Status Notification: PAUSE
[FE] threadsRequest
[FE] stackTraceRequest
OUT -> <REQ: 1> <0x1c: GETCALLSTACK>
IN <- <REP: 2> <str: message_box.js> <str: > <int: 5> <int: 0> <str: message_box.js> <str: eval> <int: 153> <int: 4> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 1> <str: TypeError: cannot read property 'constructor' of undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
[FE] scopesRequest
OUT -> <REQ: 1> <0x1d: GETLOCALS>
IN <- <REP: 2> <str: APPMGR> <tval: undefined> <str: list> <tval: undefined> <str: messageBox> <tval: undefined> <str: AppId> <tval: undefined> <str: listId> <tval: undefined> <str: info> <tval: undefined> <str: inputText> <tval: undefined> <str: listContent> <tval: undefined> <str: listData> <tval: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
[FE] variablesRequest

**Comment by harold-b** [comment]
This is possibly a duplicate of #10, which has been fixed by @StephenBloomquist.
It's all in the branch for the next version which supports duktape 2.0.0, but is not finished yet. So I'll issue a maintenance fix soon to see if this solves it.

I'll notify you here when I do to see if it helps.

**Comment by harold-b** [comment]
I publish a hotfix version which should take care of the UI freeze and another issue when using debugLog. Please give it a go and see if that resolves this.

**Comment by willi1s** [comment]
I can confirm that that fixed the problem. Great work, thanks

**Comment by harold-b** [comment]
Glad that solved it. @StephenBloomquist gets the credit on this one :wink: .
