### ISSUE TITLE
"debugLog" is not valid in the launch.json

### ISSUE THREAD

**Issue by willi1s** [harold-b/vscode-duktape-debug#14]
The new `"debugLog"` property shoes in the IDE as 'Not allowed' I guess a schema needs updating somewhere. Also when creating a debug configuration, this is not included by default, it would be good if it was with a default value of false.

**Comment by harold-b** [comment]
Yes, this was not implemented as an 'official' feature at first, I only documented it for curious minds. But as it seems it has become useful for some devs, I've already added it to the schema in the next version branch.
