### ISSUE TITLE
Improvement suggestion: Add carriage returns after logger messages

### ISSUE THREAD

**Issue by willi1s** [harold-b/vscode-duktape-debug#16]
When using the `Duktape.Logger` mechanism, any statements I log are logged to stdout with carriage returns at the end, but in VSCode they don't, although other statements do.

It would be good if this could be updated

**Comment by AdamHarte** [comment]
I also get this, but I assumed it was something I was doing on my end. Interesting to see someone else getting this.

**Comment by harold-b** [comment]
Which version of VSCode are you guys using? I can't reproduce this. **1.8.1**. Even though the current branch does not add a new line at the end of log/print notifications I still get new lines inserted by the VSCode front end when testing mandel.js (Event when substituting print with Duktape.Logger)

**Comment by willi1s** [comment]
I've not tried this for a few weeks, so I just knocked up a quick test.
Using VSCode 1.8,1 it works fine. Sorry for causing noise here.

This code:
```
    var logger = new Duktape.Logger();
    logger.l = 0;
    logger.trace('This is a trace message');
    logger.debug('This is a debug message');
    logger.info('This is an info message');
    logger.warn('This is a warn message');
    logger.error('This is an error message');
    logger.fatal('This is a fatal message');
```

Results in this in the debug console:
```
2017-01-18T10:45:37.000Z TRC sample.js: This is a trace message
2017-01-18T10:45:43.000Z DBG sample.js: This is a debug message
2017-01-18T10:45:45.000Z INF sample.js: This is an info message
2017-01-18T10:45:48.000Z WRN sample.js: This is a warn message
2017-01-18T10:45:48.000Z ERR sample.js: This is an error message
2017-01-18T10:45:48.000Z FTL sample.js: This is a fatal message
```

**Comment by harold-b** [comment]
Not a problem.
