### ISSUE TITLE
A lead for why the UI gets frozen when you sendResponse() in the .then() function

### ISSUE THREAD

**Issue by StephenBloomquist** [harold-b/vscode-duktape-debug#17]
By watching the order in which certain functions are called via debug messages (using `continueRequest()` as the test case), when things are fine `requestResume().then()` is called _**before**_  a status notification event indicating a paused state occurs. When the UI locks up the notify happens first.

**Comment by StephenBloomquist** [comment]
This would also explain why having a slow call before the next breakpoint stops the issue, it delays the time it takes for duktape to hit the next pause. 

But basically from what I'm understanding so far it's seeming like (for some reason) that it's possible for duktape to read the request, reply, execute, encounter a break, submit a pause notification, and have that notification processed by you (sending a `StoppedEvent`) faster than the `requestResume()` promise chains and `sendResponse()` is handled...?

**Comment by StephenBloomquist** [comment]
Alright, I just confirmed that's more or less what's happening. Basically the reason why your workaround fixes the problem is because it's effectively making the assumption that the write to duktape will be successful, allowing it some extra time in not having to wait to know for sure.

If I put a short (say half a second) timeout on the call to `sendResponse()` I can watch as the program executes, pauses at the breakpoint, and a half second later changes the debug UI into a running state.

**Comment by harold-b** [comment]
Thanks for the info. When I have the chance to dig bag into the codebase and refactor, I'll look into this if it needs modification.

**Comment by StephenBloomquist** [comment]
No problem~

What I think is happening is this:
1. VSCode issues a `continueRequest`/`nextRequest`/whatever
2. The called function checks if the running state is appropriate for making the request and calls `requestResume`/`requestStepIn`/whatever and proceeds to wait for duktape to send its reply confirming that it got the request. Promise is waiting for a resolve or reject at this point.
3. Duktape sends the reply and immediately begins executing.
4. `onRecieveData` gets that reply and begins parsing the message. _Meanwhile duktape has reached the next line or breakpoint and sends a status notification indicating that it's paused_, but it has to wait since `onRecieveData` is still occupied with the reply.
5. Now this is where I'm not entirely sure on how the rest happens exactly, but eventually the message is dispatched as a response and either resolve or reject is called for the promise attached to that request depending on if it's a reply or an error. BUT...
6. There's already another `onRecieveData` waiting to be executed. The whole `Resolve/Reject -> then -> callback` chain is going to have to wait until that's done.
7. `onRecieveData` in this case is the status notification (which doesn't have to go through a promise) and proceeds to run until it reaches the code where it sends a `StoppedEvent` to the debug session.
8. Finally the promise for the reply is executed but by now it's too late. The thing you needed in order to instruct the debug session that it should be paused has already occurred and then the session is instructed to unpause, effectively getting its self stuck and locking up the UI.

**Comment by StephenBloomquist** [comment]
A potential solution to this would be to queue up all the notification messages and send them once there are no more pending requests.

**Comment by StephenBloomquist** [comment]
This turned out to be more involved than I expected. Queuing the notifications ultimately didn't work in every case. So I've currently been trying out effectively handing full control of the VSCode UI state to the duktape protocol, sending a `StoppedEvent` on a pause status and a `ContinuedEvent` on a running state. This seems to be working out the best, thus far.
