### ISSUE TITLE
Debug configuration missing

### ISSUE THREAD

**Issue by willi1s** [harold-b/vscode-duktape-debug#19]
After updating Visual Studio to 1.9.0 the default debug configuration is no longer populated. I assumed this was an issue with VSCode (https://github.com/Microsoft/vscode/issues/20332), but when I raised an issue there, I was informed that a change is needed in vscode-duktape-debug.

> Please file this against the duktape debugger here https://github.com/harold-b/vscode-duktape-debug
> And let them know they need to implement configuration snippets as node is doing https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L98

**Comment by harold-b** [comment]
Thanks for notifying me. The update I already started working on addresses this, however, that one seems like it's gonna take me a bit, so I'll see if I get the chance to do a small update for this during a weekend.

Thanks.

**Comment by harold-b** [comment]
Fixed in [v0.4.1](https://github.com/harold-b/vscode-duktape-debug/tree/v0.4.1)
