### ISSUE TITLE
newbie on stage

### ISSUE THREAD

**Issue by denisdemaisbr** [harold-b/vscode-duktape-debug#20]
Hi, this extension of vscode connect directly on app (duktape engine with debugger support) OR via nodejs/proxy ?

Thanks for clarify any.

PS: i.e., what is the scene to uses it succefully.

**Comment by harold-b** [comment]
It connects directly to the target duktape app via TCP. Any app with debugger support enabled running duktape version 1.5.0/1.6.0 should work. Support for v2.0.0 is on the works but I'd like to do some refactoring before releasing that version. (If you do need support for version 2.0.0, you can [build off the 2.0.0 working branch](https://github.com/harold-b/vscode-duktape-debug/tree/duk-v2.0.0) and install the extension manually in the meantime).

See [Debug Host (Server) Instructions](https://github.com/harold-b/vscode-duktape-debug#debug-host-server-instructions) for more info.

On VSCode, you need to create a launch.json file under that .vscode directory (You can do this by clicking on the gear icon on the debug panel), and add a launch configuration to the file.

Example:

``` javascript
"version": "0.2.1",
"configurations": [
        {
            "name"        : "Duk Attach",
            "type"        : "duk",
            "request"     : "attach",
            "stopOnEntry" : false,

            "address"     : "localhost", // ip bound to the duktape runtime's listener socket
            "port"        : 9091, // Port specified on your duktape runtime's listener socket

            "localRoot"   : "${workspaceRoot}",

             // If using a transpiled language with source maps:
            "sourceMaps"  : false,
            "outDir"      : "${workspaceRoot}/bin"
        }
]
```

Let me know if this clarifies things.

**Comment by harold-b** [comment]
If there's no longer any other questions, I'll close this issue.
Please re-open it if you need anything else.
