### ISSUE TITLE
Breakpoints not hit

### ISSUE THREAD

**Issue by mike-lischke** [harold-b/vscode-duktape-debug#23]
Similarly like in #6 and #13 I have trouble with breakpoints. I'm also using the example TCP/IP code (debug-trans-socket, the unix code running on macOS) to add debug support to my test application. It's waiting for a debug connection and vscode can attach to it. However, it never stops on break points. It doesn't matter if I set "stopOnEntry" to true or false. However when I enable that setting vscode seems to be in an unconsistent state. It's still running (I can see the protocol output when setting/removing a breakpoint) but I cannot hold the execution (the Pause icon is enabled but does nothing when I click it). However, I see log output when I do:

```
[FE] pauseRequest
OUT -> <REQ: 1> <0x12: PAUSE>
IN <- <REP: 2> <EOM: 0> 
```

But that doesn't help much when the execution is not interrupted. Any idea what's missing to make break points work?

Btw: I also have added that wait loop at the start of my script, just in case, but that doesn't help either.

**Some additional info:**
I can make the debugger break on the `debugger` command in JS. I even can step through the code, but there is no line highlight showing me where I am actually. I only see the call stack and variables.

**Comment by harold-b** [comment]
Could you paste a large transport-layer log? A status notification should follow shortly after a pause request. Which is the notification which actually causes the front-end to go into break mode.

Also, which version of VSCode are you using?

Not getting any line info on the debugger command sounds like perhaps it's not resolving the source file from the string received from the debug host. Could you paste the status notifications around debugger breaks as well? Also does the document well show something like "No source found" in those cases?

Finally, could you test the JS file you are using with the vanilla 'duk' application with debugging enabled? This should rule out the case in which it is an issue with the app embedding duktape.

**Comment by mike-lischke** [comment]
OK, let me go through the list backwards. I built and ran a `duk` build with debugger support and this works nicely, provided I meet some requirements:

- The `duk` app is in the same folder as the script to be run. If I use it from a different location (e.g. from the duktape download folder it runs but breakpoints aren't hit again.
- It's important to have a short wait loop (as mentioned in one of the referenced bugs), to let vscode settle before actually setting initial breakpoints.
- It's not necessary to enable `stopOnEntry`

This setup will also have the source file name printed in the CALL STACK window.

When I run the `duk` app from a different folder (same script) but with a `debugger` command in the JS code it stops, but shows `Unknown Source` in the call stack. This setup behaves exactly like what I see with my own application. That seems to indicate it's not something I'm doing wrong in my application.

Here's what I do with a full log:
- Running `duk` app:
```bash
Mikes-iMac:duktape-2.1.0 mike$ pwd
/Users/mike/Downloads/duktape-2.1.0
Mikes-iMac:duktape-2.1.0 mike$ ./duk --debugger /Volumes/Extern/Work/MySQL/workbench/testing/test-suite/main2.js
Debugger enabled, create socket and wait for connection
Waiting for debug connection on port 9091
Debug connection established
Debugger connected, call duk_debugger_attach() and then execute requested file(s)/eval
Debugger detached, udata: 0x0
```
- The script main2.js contains:
```javascript
"strict"

var start = new Date().getTime() + 1000;
while( new Date().getTime() < start )
{}

function test() {
  var i = 123;
  debugger
  var obj = { test: 1, blah: "2" }
}
test();
```
with a breakpoint set on the line `var i = 123;`.

- The full session log is this:
```
Attached to duktape debugger.
Protocol ID: 2 20100 external unknownIN <- <NFY: 4> <int: 7> <str: DebuggerHandleFile> <str: /Volumes/Extern/Work/MySQL/workbench/testing/test-suite/main2.js> <EOM: 0> 
Finalized Initialization.
removeAllTargetBreakpoints
OUT -> <REQ: 1> <0x17: LISTBREAK>
Status Notification: PAUSE
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x13: RESUME>
IN <- <REP: 2> <EOM: 0> 
[FE] setBreakPointsRequest
OUT -> <REQ: 1> <0x18: ADDBREAK>
[FE] setBreakPointsRequest
IN <- <REP: 2> <int: 0> <EOM: 0> 
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 1> <EOM: 0> 
[FE] configurationDoneRequest
[FE] threadsRequest
Status Notification: PAUSE
[FE] threadsRequest
[FE] stackTraceRequest
OUT -> <REQ: 1> <0x1c: GETCALLSTACK>
IN <- <REP: 2> <str: /Volumes/Extern/Work/MySQL/workbench/testing/test-suite/main2.js> <str: test> <int: 11> <int: 1> <str: /Volumes/Extern/Work/MySQL/workbench/testing/test-suite/main2.js> <str: global> <int: 16> <int: 27> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
[FE] scopesRequest
OUT -> <REQ: 1> <0x1d: GETLOCALS>
IN <- <REP: 2> <str: i> <int: 123> <str: obj> <tval: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <int: 123> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
[FE] variablesRequest
[FE] continueRequest
OUT -> <REQ: 1> <0x13: RESUME>
IN <- <REP: 2> <EOM: 0> 
IN <- <NFY: 4> <int: 6> <int: 0> <EOM: 0> 
Disconnected: Target detached: ( 0 )  
[FE] disconnectRequest
```

I'm using vscode 1.12.2. I guess the log from above qualifies as "larger transport-layer log". So I hope I collected all info for to analyze the problem and am eagerly waiting for a solution or workaround :D

**Comment by mike-lischke** [comment]
I investigated a bit further. It's indeed so that as soon as there is a path in the script file name debugging is broken (even just a relative path). When I start my own app side-by-side with the script then debugging also works with that.

**Comment by harold-b** [comment]
OK, so given the log you provided it looks like the script is given as an absolute path. If I recall, absolute paths are not currently supported, but only relative paths under the [localRoot](https://github.com/harold-b/vscode-duktape-debug#example), or `outDir` if you are using source maps. You have to give the correct explicit file name to duktape when using any of the compile variants that will match a relative path under the localRoot.

**Comment by harold-b** [comment]
Also a note on stopOnEntry:

If I recall, when compiled with debug support, 'duk' does wait for a debug connection before executing the script, and when a debug client connects, duktape always pauses execution automatically until the client tells it to continue. So there should be no need for a loop when using `stopOnEntry: true` and duk.

When stopOnEntry is false, normally happens is the vscode debug client sends a resume request right after receiving the initial status notification, in doing so overriding the default behavior of breaking on connect. With stopOnEntry set to true, the default behavior is honored instead.

**Comment by mike-lischke** [comment]
> OK, so given the log you provided it looks like the script is given as an absolute path. If I recall, absolute paths are not currently supported, but only relative paths under the localRoot, or outDir if you are using source maps. You have to give the correct explicit file name to duktape when using any of the compile variants that will match a relative path under the localRoot.
Actually, I see no difference when I set the workdir in the test tool to the `localRoot` value (in the config file I use for my app I can specify that and the tool does a `cd` to that then). With this setup I can at least debug the script that is active in the vscode editor. However, it would be better if I could tell the debugger which is the main file to debug, so it always starts with that. And, to my big sorrow, I cannot get any break points working in script files I include via "duk_module_node.h". I tried everything I could think of.

> When stopOnEntry is false, normally happens is the vscode debug client sends a resume request right after receiving the initial status notification, in doing so overriding the default behavior of breaking on connect. With stopOnEntry set to true, the default behavior is honored instead.
Hmm, I did not get what you are saying here, sorry. Don't know which default behavior you mean. And with `stopOnEntry` set to true things only get worse. Now it does neither stop on entry nor on any break point. It seems to wait all the time for the connection and only when I kill the debug session in vscode it suddenly runs through the script. Very weird behavior in that case.

**Comment by harold-b** [comment]
The front-end (the vscode debug adapter) doesn't care about any main file or anything, it only respects the file paths obtained from the debug host, which are received via status notification messages at the protocol level. If the file path received in the status notification is found under the local root, then you should be able to debug it normally.

Could you post your config and a log to see what's happening?

**Comment by mike-lischke** [comment]
> The front-end (the vscode debug adapter) doesn't care about any main file or anything, it only respects the file paths obtained from the debug host, which are received via status notification messages at the protocol level. If the file path received in the status notification is found under the local root, then you should be able to debug it normally.

Yes, you are right. I misinterpreted something in my tests and thought it would matter which code editor is active, but that's not the case.

> Could you post your config and a log to see what's happening?

Sure, first the launch.json file

```json
{
    "version": "0.2.0",
    "configurations": [{
        "name": "Attach MGA",
        "type": "duk",
        "preLaunchTask": "debug mga",
        "request": "attach",

        "address": "localhost",
        "port": 9091,

        "localRoot": "${workspaceRoot}",

        "stopOnEntry": false,
        "debugLog": true
    }]
}
```

and here task.json:

```json
{
    "version": "0.1.0",
    "command": "/Volumes/Extern/Work/MySQL/workbench/testing/apps/mga/DerivedData/mga/Build/Products/Debug/mga",
    "isShellCommand": false,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [{
        "taskName": "debug mga",
        "args": ["--debugger", "main.json"]
    }]
}
```

Btw, when inserting a `debugger` command in my loaded script vscode will stop there and I can then step through the code, see variables etc. It's just that break points don't work at all there. Both the main.js file and the included file are in the same folder on disk, so it shouldn't be a path issue. Below is an animation showing a debug session. You can see a few things here:

- Need to run debug twice (the launch task is waiting for the executable which is waiting for vscode).
- Break points in the main script and `debugger` in the loaded script work.
- After the debug session ended it hangs in vscode (maybe a side effect of running it twice).

![debug](https://cloud.githubusercontent.com/assets/2398704/26547820/236e9dc8-4471-11e7-98fa-07dd1fb2bc47.gif)

**Comment by harold-b** [comment]
> Need to run debug twice (the launch task is waiting for the executable which is waiting for vscode).
There's nothing I can do in such a case. Perhaps the task should launch the executable in it's own non-child process so the it returns control immediately to vscode.

The 'debugger' directive working seems to indicate that the executable is sending source paths in status messages to the debug adapter which it can identify. However, seems breakpoints aren't working it seems the paths the front-end is sending to the duktape might not match any of the names of the scripts were compiled with.

Could you run a session, add some breakpoints then post the log? Then also a log with a debugger command and breaking on it.

**Comment by mike-lischke** [comment]
>>Need to run debug twice (the launch task is waiting for the executable which is waiting for vscode).
>There's nothing I can do in such a case. Perhaps the task should launch the executable in it's own non-child process so the it returns control immediately to vscode.

I'll see if I can make this not-waiting somehow.

> Could you run a session, add some breakpoints then post the log? Then also a log with a debugger command and breaking on it.

Here's the full log as created when doing what you see in the animation: http://pasteall.org/417813

**Comment by harold-b** [comment]
I forgot that outgoing traffic only shows the request type and not the values since they are serialized raw into the buffer.

There's one way we could show it though, if you're willing to dig a bit. Could you go into your extensions folder, where the extension is installed and look for the source file "**out/DukDbgProtocol.js**".

Then find the function `DukDbgProtocol.prototype.requestSetBreakpoint()` (line 564). and add a line such as this `this.log( `Setting breakpoint at '${file}':${line}` );` in it:

``` javascript
DukDbgProtocol.prototype.requestSetBreakpoint = function (file, line) {
        this.log( `Setting breakpoint at '${file}':${line}` ); // <- this line
        this._outBuf.clear();
        this._outBuf.writeREQ();
        this._outBuf.writeInt(Duk.CmdType.ADDBREAK);
        this._outBuf.writeString(file);
        this._outBuf.writeInt(line);
        this._outBuf.writeEOM();
        return this.sendRequest(Duk.CmdType.ADDBREAK, this._outBuf.finish());
    };
```
Then run the debugger, set a breakpoint and let me know what the message says.

**Comment by mike-lischke** [comment]
Yes, sure, I'm so thankful for your help. Now I started the debugger and it stopped at a `debugger` command in `main.js`. I then set 2 break points, one in `main.js` and one in `scenarios.js`. Here's the log for that:

```
Attached to duktape debugger.
Protocol ID: 2 20100 external unknownIN <- <NFY: 4> <int: 7> <str: DebuggerHandleFile> <str: main.js> <EOM: 0> 
Finalized Initialization.
removeAllTargetBreakpoints
OUT -> <REQ: 1> <0x17: LISTBREAK>
Status Notification: PAUSE
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x13: RESUME>
IN <- <REP: 2> <EOM: 0> 
[FE] setBreakPointsRequest
Setting breakpoint at 'scenarios.js':11
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 0> <EOM: 0> 
[FE] configurationDoneRequest
[FE] threadsRequest
Status Notification: PAUSE
[FE] threadsRequest
[FE] stackTraceRequest
OUT -> <REQ: 1> <0x1c: GETCALLSTACK>
IN <- <REP: 2> <str: main.js> <str: global> <int: 10> <int: 31> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
[FE] scopesRequest
OUT -> <REQ: 1> <0x1d: GETLOCALS>
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
[FE] variablesRequest
[FE] setBreakPointsRequest
Setting breakpoint at 'main.js':12
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 1> <EOM: 0> 
[FE] setBreakPointsRequest
Setting breakpoint at 'scenarios.js':13
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 2> <EOM: 0> 
```

PS: I have set ES6 set for my JS project so string interpolation is totally fine.

**Comment by harold-b** [comment]
OK, well at least I can determine that the 'scenario.js' breakpoint won't be recognized by duktape because it was compiled as './scenario.js' as per the other log:

>IN <- <REP: 2> <str: ./scenarios.js> <str: main> <int: 12> <int: 22> <str: undefined> <str: require> <int: 0> <int: 0> <str: main.js> <str: global> <int: 9> <int: 29> <EOM: 0>

'main.js' seems to be correct on both sides though. Do breakpoints work on main.js?

**Comment by harold-b** [comment]
>'main.js' seems to be correct on both sides though. Do breakpoints work on main.js?

Just read up again and you already answered that:
>Break points in the main script and debugger in the loaded script work.

**Comment by mike-lischke** [comment]
Hmm, but I also tried already:

    var scenarios = require("scenarios.js");

instead of

    var scenarios = require("./scenarios");

and it did not make any difference.

**Comment by harold-b** [comment]
Did you check the log with "require("scenarios.js");" ?

**Comment by mike-lischke** [comment]
Hmm, ok, what is the conclusion then? How can I make this more flexible? Is this an issue I should discuss with the duktape dev or can this be fixed in the debug adapter?

**Comment by harold-b** [comment]
> Hmm, ok, what is the conclusion then? How can I make this more flexible? Is this an issue I should discuss with the duktape dev or can this be fixed in the debug adapter?

But what did the log yield? Was the expected filename being sent to vscode? If so, the breakpoints should be working. Did they work?

**Comment by mike-lischke** [comment]
Yes, they worked when I left out the `./` prefix. I just tested also with a subfolder and also that works nicely. So it seems there's only a problem with that `./` prefix (haven't had a chance to test on Windows, so I cannot say if there are other platform specific paths that can cause trouble).

So it seems that the conclusion is: don't use a `./` prefix (and find a way to make the preLaunchTask not blocking). Nothing you have to become active with so many thanks for your help then (and for that great extension)!

**Comment by harold-b** [comment]
You're welcome, glad it was of help to you. :+1: 

> (and find a way to make the preLaunchTask not blocking)
Hopefully when I have the time to implement the **launch** command, then this won't be a problem. 

One simple workaround regarding the `require()` function would be to normalize the id [ on duk_module_node.c](https://github.com/svaarala/duktape/blob/master/extras/module-node/duk_module_node.c#L79), and register it with a normalized path removing any special path characters such as `./` and `../`.

**Comment by mike-lischke** [comment]
Ha, I already do normalization, just not that leading `./`. Will remove that now too. Thanks again :-)
