### ISSUE TITLE
How to debug debug-protocol issues?

### ISSUE THREAD

**Issue by mike-lischke** [harold-b/vscode-duktape-debug#28]
When I enable the log for the duktape-debugger extension I get (among others) this output:

OUT -> <REQ: 1> <0x1c: GETCALLSTACK>
IN <- <REP: 2> <str: main.js> <str: global> <int: 10> <int: 26> <str: eval> <str: > <int: 1> <int: 1> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 1> <str: TypeError: cannot read property 'constructor' of undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
[FE] scopesRequest
OUT -> <REQ: 1> <0x1d: GETLOCALS>
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: undefined> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <tval: undefined> <EOM: 0> 
[FE] variablesRequest

How can I find out what is actually missing (that undefined)? I tried debugging this in duktape/C but couldn't get what that undefined is actually supposed to be.

**Comment by mike-lischke** [comment]
When I knew what type is queried for a constructor I could add it, however I wonder why there is even the query for a constructor at all?

**Comment by harold-b** [comment]
> however I wonder why there is even the query for a constructor at all?

Because I like to see the type of the object on the right column of the variables view. If a constructor name is available, it's displayed, otherwise all you would get is "Object".

**Comment by harold-b** [comment]
To debug the debugger, just clone this repo run npm install and follow the instructions on [launch.json](https://github.com/harold-b/vscode-duktape-debug/blob/master/.vscode/launch.json) for the "DukDebug server" task.

**Comment by mike-lischke** [comment]
Ok, I see. I''l give it a try.

**Comment by mike-lischke** [comment]
I can't start this task. Vscode gives me the error:

> Cannot launch program '/Volumes/Extern/Work/projects/vscode-duktape-debug/src/DukDebugger.ts'; setting the 'outFiles' attribute might help.

Of course `outFiles` is set in the launch.json file for this task. JS files also exist, so I'm a bit clueless what the real problem is here.

**Comment by harold-b** [comment]
I'll have a look and let you know, some things might have changed in vscode that may have rendered the task ineffective.

**Comment by harold-b** [comment]
OK, I checked out the repo to check out the issue. The error you're getting only happens if you build from release and the outFiles dir is missing the source maps. Just run the 'build' task which will generate the source maps.
