### ISSUE TITLE
Debugger not working with duktape 2.1.1

### ISSUE THREAD

**Issue by willi1s** [harold-b/vscode-duktape-debug#29]
I am finally making the jump from Duktape v1.6.1 to v2.1.1 and I'm having issues getting the debugger to work now.

What I'm seeing is that the debugger attaches, but the source file is not reported, no breakpoints are hit, and the VS Code UI reports that it is running despite having requested it to `stopOnEntry`

I'm using:
- vscode: 1.15.1
- vscode-duktape-debug: 0.4.1

My test is as follows:
- built the `duk.exe` command line tool (supplied with duktape 2.1.1), with debug and print support
- run `duk.exe --debugger mandle.js`
- attach from vscode-duktape-debug

Launch file:
```
"configurations": [
    {
        "name": "Attach",
        "type": "duk",
        "request": "attach",
        "address": "localhost",
        "port": 9091,
        "localRoot": "${workspaceRoot}",
        "sourceMaps": false,
        "outDir": null,
        "stopOnEntry": true,
        "debugLog": true
    }
]
```

Debug log:
```
Attached to duktape debugger.
Protocol ID: 2 20101 external unknownFinalized Initialization.
removeAllTargetBreakpoints
OUT -> <REQ: 1> <0x17: LISTBREAK>
IN <- <NFY: 4> <int: 7> <str: DebuggerHandleFile> <str: mandel.js> <EOM: 0> 
Status Notification: PAUSE
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x12: PAUSE>
IN <- <REP: 2> <EOM: 0> 
[FE] setBreakPointsRequest
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 0> <EOM: 0> 
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 1> <EOM: 0> 
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 2> <EOM: 0> 
[FE] configurationDoneRequest
[FE] threadsRequest
```

I ran the same version of the vscode-duktape-debug against a version 1.6.0 `duk.exe` app, and it worked without issue:
```
Attached to duktape debugger.
Protocol ID: 1 10600 v1.6.0 unknownIN <- <NFY: 4> <int: 7> <str: DebuggerHandleFile> <str: mandel.js> <EOM: 0> 
Finalized Initialization.
removeAllTargetBreakpoints
OUT -> <REQ: 1> <0x17: LISTBREAK>
Status Notification: PAUSE
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x12: PAUSE>
IN <- <REP: 2> <EOM: 0> 
Status Notification: PAUSE
[FE] setBreakPointsRequest
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 0> <EOM: 0> 
OUT -> <REQ: 1> <0x18: ADDBREAK>
IN <- <REP: 2> <int: 1> <EOM: 0> 
OUT -> <REQ: 1> <0x18: ADDBREAK>
[FE] threadsRequest
IN <- <REP: 2> <int: 2> <EOM: 0> 
[FE] stackTraceRequest
OUT -> <REQ: 1> <0x1c: GETCALLSTACK>
IN <- <REP: 2> <str: mandel.js> <str: global> <int: 8> <int: 0> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
[FE] configurationDoneRequest
[FE] threadsRequest
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
[FE] scopesRequest
OUT -> <REQ: 1> <0x1d: GETLOCALS>
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x1e: EVAL>
IN <- <REP: 2> <int: 0> <str: [object global]> <EOM: 0> 
[FE] variablesRequest
```
This suggests something is missing from the initialisation when using Duktape 2 protocol, maybe these:
```
OUT -> <REQ: 1> <0x1c: GETCALLSTACK>
OUT -> <REQ: 1> <0x1d: GETLOCALS>
```

In order to confirm the debugger is the issue I have also run the `node duk_debug.js` Duktape debugger, and it worked as expected, note this makes the GetCallStack request:
```
Scanning source files: ..\
Found 0 source files in 1 search directories
Connecting to 127.0.0.1:9091...
Listening on *:9092
Debug transport connected
Socket.io connected
Debug version identification: 2 20101 external unknown
Debugger attached
Request BasicInfo: REQ 16 EOM
Notify AppNotify: NFY 7 "DebuggerHandleFile" "mandel.js" EOM
Unknown notify, ignoring: NFY 7 "DebuggerHandleFile" "mandel.js" EOM
Notify Status: NFY 1 1 "mandel.js" "global" 8 0 EOM
Request ListBreak: REQ 23 EOM
Request GetLocals: REQ 29 -1 EOM
Request GetCallStack: REQ 28 EOM
Reply for BasicInfo: REP 20101 "external" "unknown" 1 8 EOM
Reply for ListBreak: REP EOM
Reply for GetLocals: REP EOM
Reply for GetCallStack: REP "mandel.js" "global" 8 0 EOM
Source list request
Source request:
Source request: mandel.js
```

**Comment by willi1s** [comment]
I have tracked this down to the fact that in Duktape 2.0.3 the status notification message is sent twice, but in Duktape 2.1.0 it is only sent once.

The code in DukDebugger.js is ignoring the status message that arrives during the initialisation phase, and acts only on the one that comes later. However, now that only one arrives it is getting ignored.

This mechanism appears to be to prevent actions on status update being performed during initialisation. An updated mechanism would be to store that last status that arrives during initialisation, and if one is present at the end of initialisation, act upon it.

I've tweaked the code locally to try this and it appears to work for version 2.0.3 and 2.1.1. I'll create a PR for this update.

**Comment by harold-b** [comment]
Hi there, thanks for bringing this to my attention. I apologize I haven't been able to have a look, or at your PR. I've been extremely busy with work and simply haven't had any time for this project.

Hopefully in around 2-3 weeks time I might be able to have some free time to have a look at this and your PR. I apologize for the delays. Thanks for your patience.
