### ISSUE TITLE
key bindings

### ISSUE THREAD

**Issue by denisdemaisbr** [harold-b/vscode-duktape-debug#3]
hi!

this addon works fine!

but the key used to debug are 'conflict' with vscode.
the 'debug' key functions classic <f7,f8,..> don't works! property =[

on question: 
duk_reattach is property supported?

**Comment by harold-b** [comment]
Glad it's working fine for you :)

The key bindings in vscode are handled on the front-end. They're not affected by the debug adapter extension. [Click here to see the bindings cheat sheets.](https://code.visualstudio.com/docs/customization/keybindings)

Check ["Customizing Shortcuts"](https://code.visualstudio.com/docs/customization/keybindings#_customizing-shortcuts) to change the keys.

As for `duk_reattach` not sure which API you're speaking about here, I checked the API reference and didn't find it. Is from the working branch or something?

**Comment by denisdemaisbr** [comment]
thanks!
