### ISSUE TITLE
Debugger symbol output is messed up

### ISSUE THREAD

**Issue by mike-lischke** [harold-b/vscode-duktape-debug#31]
The title doesn't fully describe what I see, because after all I can see all variables and their values. But how they are presented in the debugger is quite strange (I'm using duktape 2.1.0). You can see this especially in the tooltip for a variable (which not only shows the value of the variable but also the names of other variables).

![debug3](https://user-images.githubusercontent.com/2398704/29811164-d135f0fe-8ca2-11e7-90ef-9e303e639008.gif)

When you use the DEBUG CONSOLE to print a value it starts like this (I ran `interfaces` there):

![debug1](https://user-images.githubusercontent.com/2398704/29810916-fa75c134-8ca1-11e7-9875-1103c0ebd615.png)

First problem: what on earth is that `{ cls: 1 ...}` trying to tell me? Can this be switched off please?
Second problem: there is no value printed for the variable `interfaces`.

However, this weird object containing `cls` has some content:

![debug2](https://user-images.githubusercontent.com/2398704/29811029-61ad7126-8ca2-11e7-9c5f-10f6edcecbdb.png)

Third problem: it lists all available variables, not just the one I want to see.
Forth problem: `__artificial`, I know it's showing internal stuff from duktape, but that isn't needed **all** the time. Can this please switched off?

**Comment by harold-b** [comment]
Hey there. Sorry I haven't been able to work on anything regarding this project in a while as I'm extremely busy trying to make ends meet. Hopefully in around 2-3 weeks time I might be able to have some free time and have a look at this and your previous request. Thanks for your patience.

**Comment by mike-lischke** [comment]
This debugger extension is such a great thing. Would be awesome if the few rough edges would be fixed. Hopefully you can find the time for that. Thanks.

**Comment by willi1s** [comment]
@mike-lischke you mentioned that you are using Duktape 2.1.0, are you not seeing issue #29 ?

**Comment by mike-lischke** [comment]
@willi1s No, I don't see this problem. I just double checked and my duktape.h file states I'm on 2.1.0.

**Comment by desertkun** [comment]
Have no experience in this whatsoever, but made a working pull request #32 
Would appreciate any input on how to publish this to the store.

**Comment by mike-lischke** [comment]
@desertkun You made a pull request. That's all you can do. @harold-b now has to merge and make a new release (hopefully soon).

**Comment by mike-lischke** [comment]
@desertkun May I ask for another thing while you are there? The [missing launch request]( #24 ) support is a pain too. I constantly have to press two shortcuts when I start debugging. Would much appreciate that (and owe you a beer) if you could fix that too 😎

**Comment by desertkun** [comment]
@mike-lischke well I can't much help you here since I don't need `launch` configuration myself. Like I said I have as much experience here as you do, and couple hours of googling will help you out.

**Comment by mike-lischke** [comment]
OK, thanks.

**Comment by harold-b** [comment]
Hey guys, appreciate the patience. We suffered catastrophic natural disasters and power and communication systems have been down for a while. There's some hot spots with mobile data from which I'm writing this. Though I want to be able to get back to this, It'll be a little while longer til I will be able to. Sorry for the inconvenience.

**Comment by mike-lischke** [comment]
Oh, I'm sorry to hear this. I hope you are safe. Take the time you need. We can certainly wait til the more important issues are solved. Good luck.

**Comment by harold-b** [comment]
Resolved with merged PR by @desertkun. No release yet as I've not had the time to properly test.
