### ISSUE TITLE
New release required

### ISSUE THREAD

**Issue by willi1s** [harold-b/vscode-duktape-debug#36]
Hi,

A number of pull requests have been accepted, but the debugger has not be released since March 2017. Any chance you could release the current master. I've been holding off on updating our platform to a newer Duktape due to incompatibilities.

Many thanks

**Comment by willi1s** [comment]
Hi, is there any chance you can progress this? It's over a year since the last release, and it would be really nice to have the latest changes included in the release?

**Comment by harold-b** [comment]
Hi @willi1s,

Sorry for the late replies. And thanks so much for your patience. Believe me, I would like to update it and release it. But unfortunately I just don't have any time available right now. I'm hoping to be able to tackle it next month, but I can't make any promises either. 

I do need to test the current branch and if I'm not mistaken the adapter code needs to be updated to be fully compatible with current VSCode versions.

Thanks for contacting me though, I really hope I get an opportunity in the near future to handle this. It's been on my radar, I haven't forgotten.

**Comment by andrewrch** [comment]
This has been done.  Thanks for raising the issue.
