### ISSUE TITLE
Source unknown in callstack

### ISSUE THREAD

**Issue by madanagopaltcomcast** [harold-b/vscode-duktape-debug#37]
Hi,

We are trying to run the vscode with duktape application in remote. On breakpoints, call stack is displayed with line numbers.But, for every frame in callstack is showing "Unknown Source". Any suggestions on how to proceed further?.

Thanks.

Regards,
Madan

**Comment by andrewrch** [comment]
Hi @madanagopaltcomcast can you try the latest version and let me know if you are still having issues?

**Comment by andrewrch** [comment]
Since this is an old issue, I'm going to resolve this. Please reopen if you're still having the same issue.
