### ISSUE TITLE
need to put debugger; in javascript to catch the breakpoints 

### ISSUE THREAD

**Issue by livrish** [harold-b/vscode-duktape-debug#39]
built make -f makefile.dukdebug as is using gcc in windows
\duktape-2.2.1>.\duk --debugger -i mandel.js

Attached to duktape debugger.
Protocol ID: 2 20201 external unknownFinalized Initialization.
removeAllTargetBreakpoints
OUT -> <REQ: 1> <0x17: LISTBREAK>
IN <- <NFY: 4> <int: 7> <str: DebuggerHandleFile> <str: mandel.js> <EOM: 0> 
Status Notification: PAUSE
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x13: RESUME>
[FE] setBreakPointsRequest
[FE] setBreakPointsRequest
IN <- <REP: 2> <EOM: 0> 
OUT -> <REQ: 1> <0x18: ADDBREAK>

{
            "name": "Attach",
            "type": "duk",
            "request": "attach",
            "address": "localhost",
            "port": 9091,
            "localRoot": "${workspaceRoot}",
            "sourceMaps": false,
            "outDir": "${workspaceRoot}",
            "stopOnEntry": false,
            "debugLog": true
       }

**Comment by andrewrch** [comment]
Hi @livrish are you still having this issue?  Could you please try with latest version and get back to me if you can still reproduce.

**Comment by andrewrch** [comment]
Since this is an old issue, I'm going to resolve this. Please reopen if you're still having the same issue.
