### ISSUE TITLE
Wrong number of params when getting BasicInfo

### ISSUE THREAD

**Issue by AdamHarte** [harold-b/vscode-duktape-debug#4]
I was getting an error, and tracked down the problem this the following line:

> DukDbgProtocol.ts  Line: #204

```
if( msg.length != 7 )
    throw new Error( "Invalid 'BasicInfo' response message." );
```

This is found inside the constructor of the DukBasicInfoResponse class. It seems on my implementation of DukTape, msg only has a length of 6, so I was getting that error thrown.

When I change it to check for a length of 6, then the debugger attaches and I start getting console logs from my JavaScript.

**Comment by harold-b** [comment]
Off the top of my head it seems like the runtime you're using is an earlier version of duktape. The current version of the debugger is meant to run on v.1.5.*.

If you see the [debugger.rst for the v1.4.2 release](https://github.com/svaarala/duktape/blob/6b024bac77d5f42e249c20cfd31483a46f30a5f4/doc/debugger.rst#basicinfo-request-0x10), it contains 6 values. [For v1.5.0, debugger.rst](https://github.com/svaarala/duktape/blob/83d557704ee63f68ab40b6fcb00995c9b3d6777c/doc/debugger.rst#basicinfo-request-0x10), shows that the protocol was changed so it expects 7 values.

Can you check which duktape runtime version you are using? If you debug the extension from source you should be able to see the [handshake message](https://github.com/svaarala/duktape/blob/master/doc/debugger.rst#version-identification) which should show the version, if you can't obtain it from the runtime itself.

**Comment by AdamHarte** [comment]
Oh yes, you are correct. Looks like we are running a really old DukTape - v1.3.0

I will try to get this updated. Thanks for your help. It is good to know that this is the problem.
