### ISSUE TITLE
Looking for maintainers?

### ISSUE THREAD

**Issue by andrewrch** [harold-b/vscode-duktape-debug#44]
Hi,

First thanks for the great extension I've learned a lot about vscode development by reading through the code.

I'm wondering you accepting PRs to this repo? From earlier comments it looks like you don't have much time to spend on it. Have noticed koush has forked and published this extension with fixes (I've raised a couple of PRs to his repo also). 

I think it would be good to have a single extension published so if you are looking for maintainers then please let me know and hopefully we can merge his fork. I intend to add tests and ci in a feature branch of my fork this week to ease the maintainence burden and make it easier for people to contribute.

Many thanks.

**Comment by harold-b** [comment]
Hi Andrew,

Yes! I am certainly looking for maintainers. It does not seem like I will have time in the foreseeable future for this anymore, and I've been trying for a while. So thanks for offering.

I've added you as a collaborator. If @koush is interested as well, please let me know.

**Comment by andrewrch** [comment]
Awesome thanks so much!
