### ISSUE TITLE
Source unknown when debugging

### ISSUE THREAD

**Issue by AndreyArsov** [harold-b/vscode-duktape-debug#8]
OK, being able to connect, pause the debugger and see the local variable and add watches.
Still however cannot get the sources to show, when I pause I get "Source Unknown Source Unavailable" in the file window, and in the stack I see the functions being called, but get "\undefined\Source Unavailable" tooltip.
Obviously I am doing something wrong, but cannot figure out what.
Tried switching the the following code:
#if 0
    if (duk_peval_string(ctx, js.c_str()) != 0) {
        printf("eval failed: %s\n", duk_safe_to_string(ctx, -1));
        exit(-1);
    }
#else
    duk_push_string(ctx, "input.js");
    duk_compile_string_filename(ctx, 0, js.c_str(), );

    duk_push_global_object(ctx);
    duk_call_method(ctx, 0);
#endif
So that the execution environment knows about the filename, and I have the same file open VSCode, but nothing help.
Any pointers appreciated.

Also Harold I see that the print statements are forwarded to the debugger in your demo, how does that work?

Thanks, Andrey.

**Comment by harold-b** [comment]
Would you add the `"debugLog" : true` option to your *launch.json* to see what the incoming "Pause" notification look like? They contain the name of the file being debugged so this can be compared with the client's source tree.

I assume you have local root set to something like this: `"localRoot" : "${workspaceRoot}"`?
If the file name from the "Pause" notification matches the subpath of the file locally from `localRoot` then it's potentially a bug.

As for the print statements, make sure you have the following macros defined in your runtime:

``` cpp
#define DUK_USE_DEBUGGER_FWD_LOGGING
#define DUK_USE_DEBUGGER_FWD_PRINTALERT
```

You can also define `DUK_USE_DEBUGGER_PAUSE_UNCAUGHT` to catch uncaught exceptions on the debugger (pretty sure this was fully implemented...can't quite recall though...)

Let me know if that helps.

**Comment by harold-b** [comment]
Actually, the correct macros are the 'OPT' based ones. These above are because I'm still using `duk_custom.h` which I believe is not the proffered way anymore, if I recall.

So the macros should be:

``` cpp
#define DUK_OPT_DEBUGGER_FWD_LOGGING
#define DUK_OPT_DEBUGGER_FWD_PRINTALERT
```

**Comment by AndreyArsov** [comment]
Thanks, this worked out, essentially I had to set the current directory of the app to the workspace directory of the vs code project, and execute the code from above.
It seems that there is sort of miscommunication again, since I see:

OUT -> <REQ: 1> <0x23: GETHEAPOBJINFO>
IN <- <ERR: 3> <int: 1> <str: unsupported command> <EOM: 0> 
Request undefined returned error: Unsupported command : unsupported command
Request undefined returned error: Unsupported command : unsupported command

In any case now the support is pretty good and usable, thanks for doing all this work.

**Comment by harold-b** [comment]
Glad you got it solved.

As for the GETHEAPOBJINFO request, you need to enable the following macro on your runtime:
`#define DUK_OPT_DEBUGGER_INSPECT`

Then you should be good to go :)

I should perhaps list all the required runtime macros for the full debugging experience on the readme as I now see it can help new users get up and running quickly. So thanks for raising these issues, I'm betting there were others who ran into them as well.

**Comment by harold-b** [comment]
BTW, I just quickly reviewed the [config documentation](https://github.com/svaarala/duktape/blob/master/doc/duk-config.rst#genconfig-option-overrides), and I had it the other way around, `DUK_OPT` has been dropped for `DUK_USE`:

>Note that DUK_OPT_xxx compiler command line options are no longer supported in Duktape 2.x; to use non-default options, run either configure.py (recommended) or genconfig.py.

**Comment by JoshMarler** [comment]
Just spend some time debugging the plugin to workout why my source maps weren't working and why I couldn't inspect heap objects. Then found this little gem. Seems like it might be nice to have a "Useful things to know" section in docs/README. I've hit a few little gotchas whilst integrating duktape debugging over at https://github.com/nick-thompson/blueprint. 

Thanks for the excellent tool @harold-b.
